### ISSUE TITLE
Display city anchor links and links to zoning code locations as links with standard text in each flyout

### ISSUE THREAD

**Issue by jridener** [opensmc/ssmc-agriculture-zoning#63]
Use CARTO css to display the more detail city anchor links and links to zoning code locations as linked text rather than the html link code. Link destinations are in the city_detail and zoning_url columns for each city's zoning boundary type.

**Comment by weverka** [comment]
Done. Note that once you go in to the CSS view for infowindows in Carto, you can't go back to the graphical infowindow picker. Here's the basic code to create hyperlinks out of data stored in the table in case that ever gets reset:

`<p><a href = {{column_name_with_URLsl}}> Display Link</a></p>`

**Comment by verythorough** [comment]
Oops, I think we were both trying to do this at the same time!  I added `target="_blank"` to the zoning code link and `target="_parent"` to the city detail one.  Since I think SSMC will be embedding this as an iframe into their WordPress site, the target attributes will keep the links from opening inside the iframe.  The `_blank` one will open in a new tab, and the `_parent` one will open in the containing page.

**Comment by weverka** [comment]
Ah, good catch!
