### ISSUE TITLE
Menlo Park zoning code review

### ISSUE THREAD

**Issue by jridener** [opensmc/ssmc-agriculture-zoning#8]
Review Menlo Park zoning code for keeping of animals (especially chickens), bees, and permitted agriculture in residential areas.

Link to the zoning code can be found here: https://docs.google.com/spreadsheets/d/199shxJaRycwVGXGR46jQNyur960dnPf-L7-lIcXyKRg/edit#gid=0

Create a new tab and use the other tabs as a template for recording what you find.

**Comment by weverka** [comment]
Read through this to get information about horses, poultry, and small mammals (rabbits/guinea pigs): http://www.codepublishing.com/CA/MenloPark/?MenloPark12/MenloPark1206.html&?f There was no information on bees or agriculture.

It appears that things are primarily handled by permits, rather than explicitly permitted and restricted by designation codes.
